language: node_js
node_js:
- 6
- 7
cache:
  directories:
  - node_modules
env:
  global:
  - SELENIUM_BROWSER=phantomjs
  - secure: tuxb6o5UfvAdrN7+wspCGpkOd4GsvhKGDUFCokiC0xgn/hmvmX4vM8jSnLGLfFNtXQE1ffEASH00sU4oh3gVTVFvzMXsyy4zGaM4uBRnRCFcuE0PiuzJg+wqXbPWp3mYeLX5XhNxImMylVs8NkSy8vEu6iOPuu4ZXx2w7ZtDCithOJNkwmVQeP7udmkGIESXkP3arZ/M5xoRttBjDe5dThhB1H7aA7Xke7b91IyCGzhXOVN4yWFMRyj+iIPg0sIo6x70ybCiaTt/b57nebQsmbAgTJlxKiWzSs1uMbrz0hKzYJeqo20N+K0+S58arpewvv6ynlSbFOaMdonVOGqQm3Ljpa5RWk6wN0XjqfFiEG+NWzMBLEEGMvMia+BWxYzMXBnViUvCT9DUehtw1muNRIAS1+Tll/X9dm+sRV6VM0ImEECvx/s14X+XUkTqUzDT19eeplnGX8YHDgHLfFYmkqbxMHeMlnYIOk1hPu/AAKE2FYFZVh7NI4/zXDa8307uElzbl6685lsj1MDmhLAWXF0Q1jM+l+h8CAT7PU8Xlm2YWi7+3EH/gAw3Jo61pWCWGk7JTQ955vg0Y7IPx6lIejo8RBjXIONqTQA2vcFu4tqnxvVzcrtvw6afOpCAiW6j3q23mxhCamcRNh4wVZ+3RCfqX+cVCcm6PxJF/Lipia8=
  - secure: keCXj5JZGLISGBFf0d5uIrh5jFVZ2cfqSeDSu9hTqxClc6l2av7+A/f8Zi1gULoMoLaSSBqoGR8faeJtNUUA0fLbYkhKk5N4zhTcuUtFVT9NcjK0vRRK2bngf4IqTFM8xlGkXmDbT+yoRha33qUX5CvT0hEFI3udJI4jJt6dTupWsaI7m/Y/qHdWRbGW4QXYjaJyhGJmDP6hxYVa2x5JGsLe8qUQnbLIM5to57hHEPQhJARw7vuc0k04m184q81nO3pJnKInCmNlo1l4npdTR3qdZD2EX54s4SjCyxAgz5g9QFDOjG1A4mjz96NOMYG/MYBB9RKK8FRsm3GQDid2dmGsNgXNLBaeCdFz11Css9MH5CHgRNwYfItEu6xmyQSdL5KW3E/ix7OZJGHFNieuipJNSPgFSj6isSsi677DEyKi+soqIIG8rox5n76OZq8BDEUfmx80NDjil0AmEgwkn0+BTKRxe4pQdW+1ciATqpG0RQanQmpiXdBVc2xtoYoPV1gOGfpD1pYJX0CDTb3LATZJPg+Cd+fLIklzQWuGTVQLe+G3AZE/FSm+RKfjokMAm0yGHnEBOuctnLv7NVk2cDaDuXG+VC5b97h9h7mgLnSeDCcRyA3xqrqgT+TnsQE3TJ1B5z5PHzPc9ac4mlO7AG/d1mtfgEF4Bbs5NhMhdtk=
